# Settings overrides for Textbox (optional)
LOG_LEVEL: INFO

SEND_HOTKEY: enter

BLOCK_HOTKEY: true
DELAY: 0.5
AUTO_PASTE_IMAGE: true
AUTO_SEND_IMAGE: true

WHITELIST: [TIM.exe, WeChat.exe, Weixin.exe, WeChatApp.exe, QQ.exe]
ENABLE_WHITELIST: true

TEXT_ST_POS: [728, 355]
TEXT_ED_POS: [2339, 800]

DEFAULT_FONT: ZhongSong.ttf
